# Generated by Django 3.2 on 2023-03-07 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_incidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='constituency',
            field=models.ForeignKey(limit_choices_to={'county_code': django.db.models.expressions.OuterRef('county_code')}, on_delete=django.db.models.deletion.CASCADE, to='geo.constituency'),
        ),
    ]
